App/models.py
from init import db 


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    ratings = db.relationship('Rating')

    def __init__(self, username, password):
        self.username = username
        self.password = password

class Rating(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id))
    game_id = db.Column(db.Integer, unique=True)
    game_name = db.Column(db.String, unique=True)
    rating = db.Column(db.Integer)

App/main.py
from init import create_app

app = create_app()

if __name__ == "__main__":
    # db.create_all()
    app.run(debug=True, port=2300)

App/views.py
from flask import Flask, Blueprint, redirect, url_for, render_template, request, redirect, session
import pandas as pd
from content_based import content_based_recommend
from SVD import SVD, hybrid
from models import User, Rating
from init import db
import random
import csv

views = Blueprint('views', __name__)

df = pd.read_csv("steam_api.csv")
df["Rating"] = ((df["Rating"].fillna(0)).astype(int)).astype(str)

# Home Page
@views.route("/", methods = ['GET','POST'])
def index():
    if session.get('logged_in'):
        with open(r'user_rating.csv','w') as f:
            header = ["ID", "User_ID","Game_id", "Game_name","Rating"]
            users = db.session.query(Rating.id, Rating.user_id, Rating.game_id,Rating.game_name,Rating.rating)
            csv_out = csv.writer(f)
            csv_out.writerow(header)
            for user in users:
                csv_out.writerow(user)

        user_name = session.get("username")
        top_Rating = df.sort_values(by = "Rating", ascending = False)[:100]
        top_forever = df.sort_values(by = "average_forever", ascending = False)[:100]
        top_positive = df.sort_values(by=['positive','negative'], ascending = False)[:100]
        user_recommend = df.iloc[SVD(session.get('user_id'),20, 100,top_Rating)['Game_index']]
        # list2 = random.sample(range(19233), 20)
        return render_template("home.html", top_Rating= top_Rating, user_recommend = user_recommend, top_forever=top_forever, top_positive= top_positive, user_name = user_name)
    else:
        return render_template("index.html")

#Register Page
@views.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        try:
            db.session.add(User(username=request.form['username'], password=request.form['password']))
            db.session.commit()
            return redirect(url_for('views.login'))
        except:
            return render_template('index.html', message="User Already Exists")
    else:
        return render_template('register.html')

#Login Page
@views.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')
    else:
        u = request.form['username']
        p = request.form['password']
        data = User.query.filter_by(username=u, password=p).first()
        if data is not None:
            session['logged_in'] = True
            session["user_id"] = data.id
            session["username"] = data.username
            return redirect(url_for('views.index'))
        return render_template('index.html', message="Incorrect Details")

#Logout 
@views.route('/logout')
def logout():
    session['logged_in'] = False
    return redirect(url_for('views.index'))


#Detail Page
@views.route("/detail/<game_id>",methods=['GET', 'POST'])
def detail(game_id):
    user_id = session.get('user_id')
    game_index = int(df[df["Game_id"]==int(game_id)].index[0])
    # list2 = random.sample(range(19233), 20)
    game_detail = df.loc[df["Game_id"]==int(game_id)].squeeze()
    game_name = str(game_detail["Game_name"])
    list_game_recommend = content_based_recommend(game_index, 20)
    list_game_hybrid = hybrid(user_id, game_index, game_name, 30, 20)['Game_index']

    if request.method == "POST":
        rating = request.form.get('rating')

        data = Rating.query.filter_by(user_id=user_id, game_id=game_id, game_name=game_name).first()
        if data is not None:
            data.rating = rating
            # Rating.query.filter_by(username='admin').update(dict(rating=rating))
            db.session.commit()
        else:
            db.session.add(Rating(user_id=user_id, game_id=game_id, game_name = game_name, rating = rating))
            db.session.commit()
        # print("Import done")

    return render_template("detail.html", game_detail=game_detail, df = df, list_game_recommend=list_game_recommend, list_game_hybrid=list_game_hybrid)

App/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Flask Login</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="icon"
      type="image/png"
      href="{{ url_for('static', filename='images/icons/favicon.ico') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='fonts/font-awesome-4.7.0/css/font-awesome.min.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='fonts/Linearicons-Free-v1.0.0/icon-font.min.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='vendor/animate/animate.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='vendor/css-hamburgers/hamburgers.min.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='vendor/animsition/css/animsition.min.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='vendor/select2/select2.min.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='vendor/daterangepicker/daterangepicker.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/util.css')}}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/main.css')}}"
    />
  </head>
  <body>
    {% block content %}{% endblock %}
    <footer>
      <p style="text-align: center">Template courtesy: colorlib</p>
    </footer>
    <script src="{{ url_for('static', filename='vendor/jquery/jquery-3.2.1.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/animsition/js/animsition.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/popper.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/select2/select2.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/daterangepicker/moment.min.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/daterangepicker/daterangepicker.js')}}"></script>
    <script src="{{ url_for('static', filename='vendor/countdowntime/countdowntime.js')}}"></script>
    <script src="{{ url_for('static', filename='js/main.js')}}"></script>
  </body>
</html>

App/templates/detail.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Game Recommendation</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
      type="text/css"
      media="all"
    />
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/jquery-1.4.2.min.js') }}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/jquery-func.js') }}"
    ></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>

  </head>
  <body>
    <!-- START PAGE SOURCE -->
    <div id="shell">
      <div id="header">
        <div class="top_image">
          <img src="{{url_for('static', filename='css/images/gamelogo.gif')}}"/>
          <p>GAME RECOMMENDATION</p>
        </div>
        <h1 id="logo"><a href="#"></a></h1>
        <div class="social">
          <span>FOLLOW US ON:</span>
          <ul>
            <li><a class="Twitter" href="#">Twitter</a></li>
            <li><a class="Facebook" href="#">Facebook</a></li>
            <li><a class="Github" href="#">Github</a></li>
          </ul>
        </div>
        <div id="sub-navigation">
          <ul>
            <li><a href="/">HOME</a></li>
          </ul>
          <div id="search">
            <form action="#" method="get" accept-charset="utf-8">
              <label for="search-field">SEARCH</label>
              <input
                type="text"
                name="search field"
                value=""
                id="search-field"
                class="blink search-field"
              />
              <input type="submit" value="GO!" class="search-button" />
            </form>
          </div>
        </div>
      </div>
      <div id="main">
        <div id="content">
          <div class="game-detail">
            <img src={{game_detail["Image_Link"]}} alt="" />
            <p>Game name: {{game_detail["Game_name"]}}</p>
            <p>Developer: {{game_detail["developer"]}}</p>
            <p>Genre: {{game_detail["genre"]}}</p>
            <p>Tags: {{game_detail["tags"]}}</p>
          </div>
          <p1>Rating for the Game</p1>
          <!-- <form action="{{ url_for('views.index')}}"> -->
          <form method="POST">
            <!-- <label for="cars">Choose a car:</label> -->
            <select name="rating" id="rating">
              {%for i in range(1,6)%}
              <option rating_number="volvo">{{i}}</option>
              {%endfor%}
            </select>
            <br><br>
            <input type="submit" value="Submit">
          </form>
        </div>
        <div class="box">
          <div class="head">
            <h2>GAME HAVE SIMILAR CONTENT</h2>
            <p class="text-right"><a href="#">See all</a></p>
          </div>
          <div class="game_slider" data-slick='{"slidesToShow": 4, "slidesToScroll": 4}'>
          {%for i in list_game_recommend%}
          <div class="game">
            <div class="game-image">
              <a href="{{ url_for('views.detail', game_id = df["Game_id"].iloc[i])}}">
                <span class="play"
                  ><span class="name">{{df["Game_name"].iloc[i]}}</span></span
                >
                <img src={{df["Image_Link"].iloc[i]}} alt="" /></a
              >
            </div>
            <div class="rating">
              <p>RATING {{df["Rating"].iloc[i] + " %"}}</p>
            </div>
          </div>
          {%endfor%}
        </div>
          <div class="box">
            <div class="head">
              <h2>IF YOU LIKE THIS GAME YOU MIGHT LIKE THESE</h2>
              <p class="text-right"><a href="#">See all</a></p>
            </div>
            <div class="game_slider" data-slick='{"slidesToShow": 4, "slidesToScroll": 4}'>
            {%for i in list_game_hybrid%}
            <div class="game">
              <div class="game-image">
                <a href="{{ url_for('views.detail', game_id = df["Game_id"].iloc[i])}}">
                  <span class="play"
                    ><span class="name">{{df["Game_name"].iloc[i]}}</span></span
                  >
                  <img src={{df["Image_Link"].iloc[i]}} alt="" /></a
                >
              </div>
              <div class="rating">
                <p>RATING {{df["Rating"].iloc[i] + " %"}}</p>
              </div>
            </div>
            {%endfor%}
          </div>
        </div>
      </div>
    </div>
    <!-- END PAGE SOURCE -->

    <script type="text/javascript" src="{{ url_for('static', filename='js/slider-func.js') }}"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>


  </body>
</html>

App/templates/home.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>Game Recommendation</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/style.css') }}"
      type="text/css"
      media="all"
    />
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/jquery-1.4.2.min.js') }}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='js/jquery-func.js') }}"
    ></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='slick/slick-theme.css') }}"/>
  </head>

  <body>
    <!-- START PAGE SOURCE -->
    <div id="shell">
      <div id="header">
        <div id="user-information">
          <p class="text-right">Hi {{user_name}}</p>
          <p class="text-right">Choose your suitable game</p>
          <p class="text-right">
            <button class="logout">
              <a href="{{ url_for('views.logout')}}">LOGOUT</a>
            </button> 
          </p>
        </div>

        <div class="top_image">
          <img src="{{url_for('static', filename='css/images/gamelogo.gif')}}"/>
          <p>GAME RECOMMENDATION</p>
        </div>
        
        <div class="social">
          <span>FOLLOW US ON:</span>
          <ul>
            <li><a class="Twitter" href="#">Twitter</a></li>
            <li><a class="Facebook" href="#">Facebook</a></li>
            <li><a class="Github" href="#">Github</a></li>
          </ul>
        </div>
        <div id="sub-navigation">
          <div id="search">
            <form action="#" method="get" accept-charset="utf-8">
              <label for="search-field">SEARCH</label>
              <input
                type="text"
                name="search field"
                value=""
                id="search-field"
                class="blink search-field"
              />
              <input type="submit" value="GO!" class="search-button" />
            </form>
          </div>
        </div>
      </div>
      <div id="main">
        <div id="content">
          <div class="box">
            <div class="head">
              <h2>TOP RATING GAME</h2>
              <p class="text-right"><a href="#">See all</a></p>
            </div>
            <div class="game_slider" data-slick='{"slidesToShow": 4, "slidesToScroll": 4}'>
            {%for i in range(0,20)%}
            <div class="game">
              <div class="game-image">
                <a href="{{ url_for('views.detail', game_id = top_Rating["Game_id"].iloc[i])}}"
                  >
                  <span class="play"><span class="name">{{top_Rating["Game_name"].iloc[i]}}</span></span>
                  <img
                    src={{top_Rating["Image_Link"].iloc[i]}}
                    alt=""
                />
              </a>
              </div>
              <div class="rating">
                <p>RATING {{top_Rating["Rating"].iloc[i] + " %"}}</p>
              </div>
            </div>
            {%endfor%}
          </div>
          </div>
          <div class="box">
            <div class="head">
              <h2>RECOMMEND FOR USER</h2>
              <p class="text-right"><a href="#">See all</a></p>
            </div>
            <div class="game_slider" data-slick='{"slidesToShow": 4, "slidesToScroll": 4}'>
            {%for i in range(0,20)%}
            <div class="game">
              <div class="game-image">
                <a href="{{ url_for('views.detail', game_id = user_recommend["Game_id"].iloc[i])}}"
                  >
                  <span class="play"><span class="name">{{user_recommend["Game_name"].iloc[i]}}</span></span>
                  <img
                    src={{user_recommend["Image_Link"].iloc[i]}}
                    alt=""
                />
              </a>
              </div>
              <div class="rating">
                <p>RATING {{user_recommend["Rating"].iloc[i] + " %"}}</p>
              </div>
            </div>
            {%endfor%}
          </div>
          </div>
          <div class="box">
            <div class="head">
              <h2>TOP GAME BY POSITIVE SCORE</h2>
              <p class="text-right"><a href="#">See all</a></p>
            </div>
            <div class="game_slider" data-slick='{"slidesToShow": 4, "slidesToScroll": 4}'>
            {%for i in range(0,20)%}
            <div class="game">
              <div class="game-image">
                <a href="{{ url_for('views.detail', game_id = top_positive["Game_id"].iloc[i])}}"
                  >
                  <span class="play"><span class="name">{{top_positive["Game_name"].iloc[i]}}</span></span>
                  <img
                    src={{top_positive["Image_Link"].iloc[i]}}
                    alt=""
                /></a>
              </div>
              <div class="rating">
                <p>POSITIVE RATING {{top_positive["positive"].iloc[i]}}</p>
              </div>
            </div>
            {%endfor%}
          </div>
          </div>
          <div class="box">
            <div class="head">
              <h2>TOP GAME PLAYER PLAY MOST</h2>
              <p class="text-right"><a href="#">See all</a></p>
            </div>
            <div class="game_slider" data-slick='{"slidesToShow": 4, "slidesToScroll": 4}'>
            {%for i in range(0,20)%}
            <div class="game">
              <div class="game-image">
                <a href="{{ url_for('views.detail', game_id = top_forever["Game_id"].iloc[i])}}"
                  >
                  <span class="play"><span class="name">{{top_forever["Game_name"].iloc[i]}}</span></span>
                  <img
                    src={{top_forever["Image_Link"].iloc[i]}}
                    alt=""
                /></a>
              </div>
              <div class="rating">
                <p>RATING {{top_forever["Rating"].iloc[i] + " %"}}</p>
              </div>
            </div>
            {%endfor%}
          </div>
          </div>
        </div>
    </div>
    <!-- END PAGE SOURCE -->

  <script type="text/javascript" src="{{ url_for('static', filename='js/slider-func.js') }}"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='slick/slick.min.js') }}"></script>
  


  </body>
</html>

App/templates/index.html
{% extends 'base.html' %} {% block content %}
<div class="limiter">
  <style>
    body {
      background-color: rgb(12, 12, 12);
    }
  </style>
  <div class="container-login100">
    <div class="wrap-login100 p-t-50 p-b-90">
      <!-- <span class="login100-form-title p-b-51"> {{ "Hello" }} </span> -->
      <img
        src="{{url_for('static', filename='css/images/hello.gif')}}"
        alt="Game Title"
        width="390"
        height="220"
      />

      <div class="container-login100-form-btn m-t-17">
        <button class="login100-form-btn">
          <a class="login100-form-btn" href="{{ url_for('views.login')}}"
            >Login</a
          >
        </button>
      </div>
      <div class="container-login100-form-btn m-t-17">
        <button class="login100-form-btn">
          <a class="login100-form-btn" href="{{ url_for('views.register')}}"
            >Register</a
          >
        </button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

App/templates/login.html
{% extends 'base.html' %} {% block content %}
<div class="limiter">
  <style>
    body {
      background-color: rgb(12, 12, 12);
    }
  </style>
  <body>
    <div class="container-login100">
      <div class="wrap-login100 p-t-50 p-b-90">
        <form
          class="login100-form validate-form flex-sb flex-w"
          method="POST"
          action="/login"
        >
          <span class="login100-form-title p-b-51"> Login </span>
          <div
            class="wrap-input100 validate-input m-b-16"
            data-validate="Username is required"
          >
            <input
              class="input100"
              type="text"
              name="username"
              placeholder="Username"
            />
            <span class="focus-input100"></span>
          </div>
          <div
            class="wrap-input100 validate-input m-b-16"
            data-validate="Password is required"
          >
            <input
              class="input100"
              type="password"
              name="password"
              placeholder="Password"
            />
            <span class="focus-input100"></span>
          </div>
          <div class="flex-sb-m w-full p-t-3 p-b-24">
            <div>
              <a href="{{ url_for('views.register')}}" class="txt1">
                Sign Up
              </a>
            </div>
          </div>
          <div class="container-login100-form-btn m-t-17">
            <button class="login100-form-btn">Login</button>
          </div>
        </form>
      </div>
    </div>
  </body>
</div>
{% endblock %}

App/templates/register.html
{% extends 'base.html' %} {% block content %}
<div class="limiter">
  <style>
    body {
      background-color: rgb(12, 12, 12);
    }
  </style>
  <div class="container-login100">
    <div class="wrap-login100 p-t-50 p-b-90">
      <form
        class="login100-form validate-form flex-sb flex-w"
        method="POST"
        action="/register"
      >
        <span class="login100-form-title p-b-51"> Register </span>
        <div
          class="wrap-input100 validate-input m-b-16"
          data-validate="Username is required"
        >
          <input
            class="input100"
            type="text"
            name="username"
            placeholder="Username"
          />
          <span class="focus-input100"></span>
        </div>
        <div
          class="wrap-input100 validate-input m-b-16"
          data-validate="Password is required"
        >
          <input
            class="input100"
            type="password"
            name="password"
            placeholder="Password"
          />
          <span class="focus-input100"></span>
        </div>
        <div class="flex-sb-m w-full p-t-3 p-b-24">
          <div>
            <a href="{{url_for('views.login')}}" class="txt1"> Log In </a>
          </div>
        </div>
        <div class="container-login100-form-btn m-t-17">
          <button class="login100-form-btn">Register</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}